//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkademiPlus_Transportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_About
    {
        public int AboutID { get; set; }
        public string SmallTitle { get; set; }
        public string LargeTitle { get; set; }
        public string AboutContent { get; set; }
        public string AboutImage { get; set; }
        public string AboutImage2 { get; set; }
        public string AboutTitle { get; set; }
        public string AboutContent2 { get; set; }
    }
}
