//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkademiPlus_Transportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOffers
    {
        public int OfferID { get; set; }
        public string OfferTitle { get; set; }
        public string OfferContent { get; set; }
        public string OfferIcon { get; set; }
    }
}
